/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as About1017RouteImport } from './routes/about-1017'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReleaseNameRouteImport } from './routes/release.$name'
import { Route as ArtistNameRouteImport } from './routes/artist.$name'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminReleasesRouteImport } from './routes/admin/releases'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminFounderSpotlightRouteImport } from './routes/admin/founder-spotlight'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminArtistsRouteImport } from './routes/admin/artists'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const About1017Route = About1017RouteImport.update({
  id: '/about-1017',
  path: '/about-1017',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNameRoute = ReleaseNameRouteImport.update({
  id: '/release/$name',
  path: '/release/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistNameRoute = ArtistNameRouteImport.update({
  id: '/artist/$name',
  path: '/artist/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReleasesRoute = AdminReleasesRouteImport.update({
  id: '/admin/releases',
  path: '/admin/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFounderSpotlightRoute = AdminFounderSpotlightRouteImport.update({
  id: '/admin/founder-spotlight',
  path: '/admin/founder-spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/admin/artists',
  path: '/admin/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-1017': typeof About1017Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/founder-spotlight': typeof AdminFounderSpotlightRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/artist/$name': typeof ArtistNameRoute
  '/release/$name': typeof ReleaseNameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-1017': typeof About1017Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/founder-spotlight': typeof AdminFounderSpotlightRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/artist/$name': typeof ArtistNameRoute
  '/release/$name': typeof ReleaseNameRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-1017': typeof About1017Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/founder-spotlight': typeof AdminFounderSpotlightRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/artist/$name': typeof ArtistNameRoute
  '/release/$name': typeof ReleaseNameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-1017'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/artists'
    | '/admin/dashboard'
    | '/admin/founder-spotlight'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/media'
    | '/admin/releases'
    | '/admin/subscribers'
    | '/artist/$name'
    | '/release/$name'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-1017'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/artists'
    | '/admin/dashboard'
    | '/admin/founder-spotlight'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/media'
    | '/admin/releases'
    | '/admin/subscribers'
    | '/artist/$name'
    | '/release/$name'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about-1017'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/artists'
    | '/admin/dashboard'
    | '/admin/founder-spotlight'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/media'
    | '/admin/releases'
    | '/admin/subscribers'
    | '/artist/$name'
    | '/release/$name'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  About1017Route: typeof About1017Route
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFounderSpotlightRoute: typeof AdminFounderSpotlightRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminReleasesRoute: typeof AdminReleasesRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  ArtistNameRoute: typeof ArtistNameRoute
  ReleaseNameRoute: typeof ReleaseNameRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about-1017': {
      id: '/about-1017'
      path: '/about-1017'
      fullPath: '/about-1017'
      preLoaderRoute: typeof About1017RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release/$name': {
      id: '/release/$name'
      path: '/release/$name'
      fullPath: '/release/$name'
      preLoaderRoute: typeof ReleaseNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$name': {
      id: '/artist/$name'
      path: '/artist/$name'
      fullPath: '/artist/$name'
      preLoaderRoute: typeof ArtistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/releases': {
      id: '/admin/releases'
      path: '/admin/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AdminReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/founder-spotlight': {
      id: '/admin/founder-spotlight'
      path: '/admin/founder-spotlight'
      fullPath: '/admin/founder-spotlight'
      preLoaderRoute: typeof AdminFounderSpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/admin/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  About1017Route: About1017Route,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminArtistsRoute: AdminArtistsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFounderSpotlightRoute: AdminFounderSpotlightRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminReleasesRoute: AdminReleasesRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  ArtistNameRoute: ArtistNameRoute,
  ReleaseNameRoute: ReleaseNameRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
