-- Add a sequential number column to artist_applications starting at 34333
ALTER TABLE public.artist_applications 
ADD COLUMN IF NOT EXISTS application_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 34333);

-- Add a generated column that formats the sequence into the required string format
ALTER TABLE public.artist_applications 
ADD COLUMN IF NOT EXISTS application_id TEXT GENERATED ALWAYS AS ('The New 1017 Records-' || application_number) STORED;
