// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = 
    import.meta.env.VITE_SUPABASE_URL || 
    process.env.SUPABASE_URL || 
    process.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please set these in your environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _isAvailable = true;

const noopChannel = {
  on: () => noopChannel,
  subscribe: (cb?: (status: string, err?: Error) => void) => {
    if (cb) setTimeout(() => cb("CHANNEL_ERROR", new Error("Supabase is offline")), 0);
    return noopChannel;
  },
  unsubscribe: () => Promise.resolve(),
};

if (typeof window !== "undefined") {
  const urlStr = import.meta.env.VITE_SUPABASE_URL || "";
  const apiKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || "";
  if (urlStr) {
    // Perform dynamic connectivity check to verify if the custom Supabase endpoint is reachable (handles fresh projects or pending DNS)
    _isAvailable = false;
    fetch(`${urlStr}/rest/v1/`, { 
      method: "HEAD", 
      headers: apiKey ? { apikey: apiKey } : undefined 
    })
      .then(() => {
        _isAvailable = true;
      })
      .catch(() => {
        console.warn(`[Supabase] Service endpoint ${urlStr} is currently unreachable. Realtime websocket channels temporarily disabled. Retrying DNS in background...`);
        
        // Keep checking in background until service resolves
        const interval = setInterval(() => {
          fetch(`${urlStr}/rest/v1/`, { 
            method: "HEAD", 
            headers: apiKey ? { apikey: apiKey } : undefined 
          })
            .then(() => {
              _isAvailable = true;
              console.log(`[Supabase] Service connected successfully! Realtime websockets enabled.`);
              clearInterval(interval);
            })
            .catch(() => {});
        }, 5000);
      });
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (prop === "channel") {
      if (!_isAvailable) {
        return () => noopChannel;
      }
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

